server {
    listen 80;
    listen [::]:80;
    server_name tristonarmstrong.com www.tristonarmstrong.com;

    root /var/www/Personal-Site/dist/client;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
